# Site settings
title: Charlie Le blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "https://charlietle.github.io"
twitter_username: charlietle
github_username:  charlietle

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
